language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
before_script: sudo apt-get install pychecker pylint pep8 rpm python-rpm
install:
  - pip install pybuilder --use-mirrors
  - pyb --debug install_dependencies
script: "pyb --debug"
